version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ysp_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8002:80

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - ./api/:/app/api
    depends_on:
      - db
    expose:
      - 9000

  ui:
    build: ./ui
    container_name: ui
    restart: always
    volumes:
      - ./ui/:/app/ui
    expose:
      - 9001

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"